name: On PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-commits:
    uses: ./.github/workflows/workflow_lint_commits.yml
    with:
      from: ${{ github.event.pull_request.base.sha }}
      to: ${{ github.event.pull_request.head.sha }}

  lint:
    uses: ./.github/workflows/workflow_lint.yml

  test:
    uses: ./.github/workflows/workflow_test.yml

