name: On push to main

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  lint-commits:
    uses: ./.github/workflows/workflow_lint_commits.yml

  lint:
    uses: ./.github/workflows/workflow_lint.yml

  test:
    uses: ./.github/workflows/workflow_test.yml

  push:
    needs:
      - lint-commits
      - lint
      - test
    uses: ./.github/workflows/workflow_push_to_ecr.yml
    with:
      tags: main
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      iam_role: ${{ secrets.AWS_IAM_ROLE }}
      aws_region: ${{ secrets.AWS_REGION }}
