name: On PR

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-commits:
    uses: ./.github/workflows/workflow_lint_commits.yml
    with:
      from: ${{ github.event.pull_request.base.sha }}
      to: ${{ github.event.pull_request.head.sha }}

  lint:
    uses: ./.github/workflows/workflow_lint.yml

  test:
    uses: ./.github/workflows/workflow_test.yml

  push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs:
      - lint-commits
      - lint
      - test
    uses: ./.github/workflows/workflow_push_to_ecr.yml
    with:
      tags: pr-${{ github.event.number }}
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      iam_role: ${{ secrets.AWS_IAM_ROLE }}
      aws_region: ${{ secrets.AWS_REGION }}
